# Generated by Django 5.2.16 on 2026-07-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('manufacturer', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD'), ('Apple', 'Apple'), ('Qualcomm', 'Qualcomm'), ('MediaTek', 'MediaTek'), ('Samsung', 'Samsung'), ('Other', 'Другой')], max_length=50, verbose_name='Производитель')),
                ('series', models.CharField(blank=True, max_length=100, verbose_name='Серия')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение')),
                ('cores', models.PositiveIntegerField(blank=True, null=True, verbose_name='Всего ядер')),
                ('performance_cores', models.PositiveIntegerField(blank=True, null=True, verbose_name='Performance-ядра')),
                ('efficiency_cores', models.PositiveIntegerField(blank=True, null=True, verbose_name='Efficiency-ядра')),
                ('threads', models.PositiveIntegerField(blank=True, null=True, verbose_name='Потоки')),
                ('base_clock', models.FloatField(blank=True, null=True, verbose_name='Базовая частота (GHz)')),
                ('boost_clock', models.FloatField(blank=True, null=True, verbose_name='Boost частота (GHz)')),
                ('tdp', models.PositiveIntegerField(blank=True, null=True, verbose_name='TDP (Вт)')),
                ('socket', models.CharField(blank=True, max_length=50, verbose_name='Сокет')),
                ('release_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выхода')),
                ('lithography', models.CharField(blank=True, max_length=50, verbose_name='Техпроцесс')),
                ('integrated_graphics', models.BooleanField(default=False, verbose_name='Встроенная графика')),
                ('igpu_name', models.CharField(blank=True, max_length=100, verbose_name='Название iGPU')),
                ('overall_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Общий рейтинг')),
                ('overall_score_approx', models.BooleanField(default=False, verbose_name='Общий рейтинг приблизительный')),
                ('cinebench_r23_single', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cinebench R23 Single')),
                ('cinebench_r23_single_approx', models.BooleanField(default=False, verbose_name='Cinebench R23 Single приблизительный')),
                ('cinebench_r23_multi', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cinebench R23 Multi')),
                ('cinebench_r23_multi_approx', models.BooleanField(default=False, verbose_name='Cinebench R23 Multi приблизительный')),
                ('cinebench_2024_single', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cinebench 2024 Single')),
                ('cinebench_2024_single_approx', models.BooleanField(default=False, verbose_name='Cinebench 2024 Single приблизительный')),
                ('cinebench_2024_multi', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cinebench 2024 Multi')),
                ('cinebench_2024_multi_approx', models.BooleanField(default=False, verbose_name='Cinebench 2024 Multi приблизительный')),
                ('geekbench6_single', models.PositiveIntegerField(blank=True, null=True, verbose_name='Geekbench 6 Single')),
                ('geekbench6_single_approx', models.BooleanField(default=False, verbose_name='Geekbench 6 Single приблизительный')),
                ('geekbench6_multi', models.PositiveIntegerField(blank=True, null=True, verbose_name='Geekbench 6 Multi')),
                ('geekbench6_multi_approx', models.BooleanField(default=False, verbose_name='Geekbench 6 Multi приблизительный')),
                ('passmark', models.PositiveIntegerField(blank=True, null=True, verbose_name='PassMark')),
                ('passmark_approx', models.BooleanField(default=False, verbose_name='PassMark приблизительный')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Процессор',
                'verbose_name_plural': 'Процессоры',
                'ordering': ['-release_year', 'name'],
            },
        ),
    ]
