# Generated by Django 5.2.17 on 2026-08-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='architecture',
            field=models.CharField(blank=True, max_length=100, verbose_name='Архитектура (ядро)'),
        ),
        migrations.AddField(
            model_name='processor',
            name='bus',
            field=models.CharField(blank=True, max_length=100, verbose_name='Шина'),
        ),
        migrations.AddField(
            model_name='processor',
            name='category',
            field=models.CharField(blank=True, choices=[('Desktop', 'Десктопный'), ('Mobile', 'Мобильный'), ('Server', 'Серверный'), ('Other', 'Другой')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='processor',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='Инструкции и технологии'),
        ),
        migrations.AddField(
            model_name='processor',
            name='integrated_modules',
            field=models.TextField(blank=True, verbose_name='Встроенные модули'),
        ),
        migrations.AddField(
            model_name='processor',
            name='l1_cache',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кэш L1'),
        ),
        migrations.AddField(
            model_name='processor',
            name='l2_cache',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кэш L2'),
        ),
        migrations.AddField(
            model_name='processor',
            name='l3_cache',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кэш L3'),
        ),
        migrations.AddField(
            model_name='processor',
            name='max_temp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. температура (°C)'),
        ),
        migrations.AddField(
            model_name='processor',
            name='memory_support',
            field=models.CharField(blank=True, max_length=200, verbose_name='Поддержка памяти (RAM)'),
        ),
        migrations.AddField(
            model_name='processor',
            name='other_features',
            field=models.TextField(blank=True, verbose_name='Другие особенности'),
        ),
        migrations.AddField(
            model_name='processor',
            name='pcie',
            field=models.CharField(blank=True, max_length=100, verbose_name='PCIe'),
        ),
        migrations.AddField(
            model_name='processor',
            name='transistors',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Транзисторов (млн)'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='igpu_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название iGPU'),
        ),
    ]
